// <auto-generated />
namespace WebLog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fixadvertisements2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixadvertisements2));
        
        string IMigrationMetadata.Id
        {
            get { return "201610132224101_fixadvertisements2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
